# Generated by Django 5.0.3 on 2024-08-08 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, null=True, unique=True)),
                ('school_name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('school_number', models.IntegerField(null=True)),
                ('school_type', models.CharField(max_length=10, null=True)),
                ('school_level', models.JSONField(null=True)),
                ('school_classes', models.JSONField(null=True)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('student_sexe', models.CharField(blank=True, max_length=10, null=True)),
                ('student_class', models.CharField(blank=True, max_length=10, null=True)),
                ('student_number', models.IntegerField(blank=True, null=True)),
                ('student_birthday_date', models.DateField(blank=True, null=True)),
                ('register_date', models.DateTimeField(blank=True, null=True)),
                ('student_register_number', models.IntegerField(blank=True, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher_lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher_sexe', models.CharField(blank=True, max_length=10, null=True)),
                ('teacher_classes', models.JSONField(blank=True, null=True)),
                ('teacher_number', models.IntegerField(blank=True, null=True)),
                ('teacher_birthday', models.DateField(blank=True, null=True)),
                ('teacher_register_date', models.DateField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('school', 'School'), ('student', 'Student')], default='school', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.JSONField()),
                ('subject', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
