# Generated by Django 5.0.3 on 2024-08-08 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoFamiliale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_lastname', models.CharField(max_length=100)),
                ('mother_profession', models.CharField(max_length=100)),
                ('mother_number', models.IntegerField()),
                ('father_name', models.CharField(max_length=100)),
                ('father_lastname', models.CharField(max_length=100)),
                ('father_profession', models.CharField(max_length=100)),
                ('father_number', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
