# Generated by Django 3.2.12 on 2025-08-09 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20250805_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='annee_scolaire',
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='base.anneescolaire')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='base.etablissement')),
                ('professeur_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.professeur')),
            ],
            options={
                'unique_together': {('etablissement', 'annee_scolaire', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='etablissement',
            name='annees_scolaires',
            field=models.ManyToManyField(blank=True, to='base.AnneeScolaire'),
        ),
        migrations.AddField(
            model_name='professeur',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='professeurs', to='base.Classe'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.classe'),
        ),
    ]
