# Generated by Django 5.0.3 on 2024-08-09 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_infofamiliale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('classe', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=150)),
                ('course', models.BooleanField()),
                ('course_start', models.DateTimeField()),
                ('course_end', models.DateTimeField()),
                ('activities', models.TextField()),
                ('students_missing', models.JSONField()),
                ('remarks', models.TextField()),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matiere', to='base.matiere')),
                ('nameSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nameSchool', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
