# Generated by Django 3.2.12 on 2026-06-18 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20250809_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anneescolaire',
            options={'ordering': ['-date_debut'], 'verbose_name': 'Année scolaire', 'verbose_name_plural': 'Années scolaires'},
        ),
        migrations.AlterModelOptions(
            name='classe',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='matiere',
        ),
        migrations.AlterField(
            model_name='professeur',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professeurs', to='base.etablissement'),
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('etablissement', 'annee_scolaire', 'nom', 'niveau', 'section')},
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='base.etablissement')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'unique_together': {('nom', 'etablissement')},
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='matieres',
            field=models.ManyToManyField(blank=True, related_name='classes', to='base.Matiere'),
        ),
        migrations.AddField(
            model_name='professeur',
            name='matieres',
            field=models.ManyToManyField(blank=True, related_name='professeurs', to='base.Matiere'),
        ),
    ]
