# Generated by Django 5.0.3 on 2024-08-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='teacher_subjects',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('school', 'School'), ('student', 'Student'), ('teacher', 'Teacher'), ('parent', 'Parent')], default='school', max_length=10),
        ),
    ]
