# Generated by Django 3.2.12 on 2026-06-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_cours_salle'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='date_specifique',
            field=models.DateField(blank=True, help_text='Date spécifique pour ce cours (ex: cours exceptionnel)', null=True),
        ),
    ]
