# Generated by Django 5.0.3 on 2024-08-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_course_course_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
