# Generated by Django 3.2.12 on 2026-06-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_cours_date_specifique'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='type_cours',
            field=models.CharField(choices=[('regulier', 'Régulier'), ('specifique', 'Spécifique'), ('exceptionnel', 'Exceptionnel')], default='regulier', help_text='Régulier (chaque semaine) ou Spécifique (date unique)', max_length=20),
        ),
    ]
