# Generated by Django 3.2.12 on 2026-07-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_cours_type_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text="Latitude de l'établissement", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text="Longitude de l'établissement", max_digits=11, null=True),
        ),
    ]
