# Generated by Django 5.0.3 on 2024-08-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_course_course_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='matiere',
            field=models.CharField(max_length=100),
        ),
    ]
