# Generated by Django 3.2.12 on 2026-07-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20260704_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='coordinates_updated_at',
            field=models.DateTimeField(blank=True, help_text='Date de dernière mise à jour des coordonnées', null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='coordinates_verified',
            field=models.BooleanField(default=False, help_text='Indique si les coordonnées ont été vérifiées'),
        ),
    ]
