# Generated by Django 5.0.3 on 2024-08-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_course_course_alter_course_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='nameSchool',
            field=models.CharField(max_length=100),
        ),
    ]
