# Generated by Django 3.2.12 on 2026-07-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20260704_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text="Photo de profil de l'utilisateur", null=True, upload_to='profiles/'),
        ),
    ]
