# Generated by Django 5.0.3 on 2024-08-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_course_nameschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='school',
            field=models.CharField(max_length=100),
        ),
    ]
