# Generated by Django 5.0.3 on 2024-08-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('student', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=100)),
                ('school_year', models.DateField()),
                ('semester', models.CharField(max_length=10)),
                ('session_start', models.DateField()),
                ('session_end', models.DateField()),
                ('matiere', models.CharField(max_length=50)),
                ('note', models.FloatField()),
                ('coef', models.IntegerField()),
            ],
        ),
    ]
