# Generated by Django 3.2.12 on 2026-09-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_evaluation_note_periode'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoleOSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('adresse', models.CharField(blank=True, max_length=500)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('type_ecole', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(default='osm', max_length=20)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'École OSM',
                'verbose_name_plural': 'Écoles OSM',
            },
        ),
        migrations.AddIndex(
            model_name='ecoleosm',
            index=models.Index(fields=['latitude', 'longitude'], name='base_ecoleo_latitud_4b4ffd_idx'),
        ),
    ]
