# Generated by Django 5.0.3 on 2024-08-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='school_year',
            field=models.CharField(max_length=10),
        ),
    ]
