# Generated by Django 5.0.3 on 2024-08-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_customuser_student_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('student', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=100)),
                ('motif', models.TextField()),
                ('somme', models.IntegerField()),
                ('reste', models.IntegerField()),
            ],
        ),
    ]
