# Generated by Django 5.0.3 on 2024-08-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_registrationdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdata',
            name='classes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='prof_de',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='classe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='student',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
